import 'package:tinder/domain/model/index.dart';
import '../enum/index.dart';
import 'package:tinder/core/utils/string_extension.dart';

class UserModel {
  String id;
  String title;
  String firstName;
  String lastName;
  Gender gender;
  DateTime dateOfBirth;
  String? email;
  DateTime? registerDate;
  String? phone;
  String? picture;
  LocationModel? location;
  UserModel(
      {required this.id,
      required this.title,
      required this.firstName,
      required this.lastName,
      required this.gender,
      required this.dateOfBirth,
      this.email,
      this.registerDate,
      this.phone,
      this.picture,
      this.location});

  factory UserModel.fromJson({required Map<String, dynamic> json}) {
    return UserModel(
        id: json['id'],
        title: json['title'],
        firstName: json['firstName'],
        lastName: json['lastName'],
        gender: getGenderFromValue(genderValue: (json['gender'] ?? '')),
        dateOfBirth:
            json['dateOfBirth']?.toString().fromISOStringToDateTime() ??
                DateTime.now(),
        email: json['email'],
        registerDate:
            json['registerDate']?.toString().fromISOStringToDateTime() ??
                DateTime.now(),
        phone: json['phone'],
        picture: json['picture'],
        location: json['location'] != null
            ? LocationModel.fromJson(json: json['location'])
            : null);
  }
}

/*
{
id: string(autogenerated)
title: string("mr", "ms", "mrs", "miss", "dr", "")
firstName: string(length: 2-50)
lastName: string(length: 2-50)
gender: string("male", "female", "other", "")
email: string(email)
dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
registerDate: string(autogenerated)
phone: string(phone number - any format)
picture: string(url)
location: object(Location)
}
 */